<a href="https://colab.research.google.com/github/EngrIBGIT/Projects_Deep_Learning_PyTorch/blob/main/Project_Deep_Learning_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')

x = torch.rand(5, 3).to(device)


x = torch.rand(5, 3, device=device)


### Autograd:

Package provide automatic differentiation for all operations on Tensors.
Torch.autograd is an engine for computing the vector-jacobian product. It computes partial derivatives while applying the chain rule.

`Set requires_grad = True:`

In [ ]:
import torch

# requires_grad = True --> tracks all operations on the tensor.
x = torch.randn(3, requires_grad=True)
y = x + 2

# y was created as a result of an operation, so it has a grad_fn attribute.
# grad_fn: references a Function that has created the Tensor
print(x) # created by the user --> grad_fn is None
print(y)
print(y.grad_fn)

tensor([-1.5407, -1.0599,  0.1572], requires_grad=True)
tensor([0.4593, 0.9401, 2.1572], grad_fn=<AddBackward0>)


In [ ]:
# Do more operations on y
z = y * y * 3
print(z)
z = z.mean()
print(z)

tensor([ 0.6329,  2.6513, 13.9610], grad_fn=<MulBackward0>)
tensor(5.7484, grad_fn=<MeanBackward0>)


In [ ]:
z.backward() # dz/dx
print(x.grad)

tensor([0.9186, 1.8802, 4.3145])
