<a href="https://colab.research.google.com/github/EngrIBGIT/Projects_Deep_Learning_PyTorch/blob/main/Project_Deep_Learning_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pytorch Fundamentals

## Resources
`Notebook:` [Pytorch](https://www.learnpytorch.io/00_pytorch_fundamentals/)

`Guided Learning:` [Udacity Deep Learning Pytorch](https://www.udacity.com/course/deep-learning-pytorch--ud188?irclickid=3u50vqRulxyPWoN36uVfJR3zUkFSahxmE2bO040&irgwc=1&utm_source=affiliate&utm_medium=&aff=259799&utm_term=&utm_campaign=_gtc_www_classcentral_com_&utm_content=&adid=788805)

[Deep Learning: CS 182 Spring 2021](https://www.youtube.com/playlist?list=PL_iWQOsE6TfVmKkQHucjPAoRtIJYt8a5A)


In [ ]:
!nvidia-smi

Wed Oct  9 14:11:54 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   45C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

import warnings
warnings.filterwarnings('ignore')

In [ ]:
print(torch.__version__)

2.4.1+cu121


## Introduction to Tensors: Tensors are the main building blocks of pytorch

#### Creating Tensors; Pytorch tensors are created using `torch.Tensor()` = [Create Tensor](https://pytorch.org/docs/stable/tensors.html)

In [3]:
# Scalar: A way to create tensor in pytorch, has no dimensions its a single number

scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor as python int
scalar.item()

7

In [ ]:
# vector; Typically has more than one dimention

vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX:
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

__Random Tensors:__

*Why random tensors?*

`Random tensors are important because many neural networks learn by starting with tensor full of numbers and then adjust those random numbers to better represent data`

Start with random numbers --> Look at data --> update random numbers --> Look at data --> update random numbers -->

[Torch random tensors](https://pytorch.org/docs/stable/generated/torch.rand.html)

In [ ]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4871, 0.1863, 0.5635, 0.8462],
        [0.8449, 0.1131, 0.8301, 0.1739],
        [0.9541, 0.5147, 0.2897, 0.6153]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor2 = torch.rand(2, 5, 6)
random_tensor2

tensor([[[0.8799, 0.8630, 0.3519, 0.4966, 0.7470, 0.0569],
         [0.7438, 0.3642, 0.7589, 0.8155, 0.6022, 0.7762],
         [0.5549, 0.1198, 0.8143, 0.1073, 0.6836, 0.3066],
         [0.2271, 0.1944, 0.2165, 0.4513, 0.9756, 0.2348],
         [0.1249, 0.0990, 0.2549, 0.1587, 0.9944, 0.0285]],

        [[0.3677, 0.5970, 0.3848, 0.5676, 0.1055, 0.2327],
         [0.0548, 0.4558, 0.2897, 0.3749, 0.0372, 0.0352],
         [0.9546, 0.0060, 0.2680, 0.9677, 0.6615, 0.0415],
         [0.8682, 0.5734, 0.5947, 0.9019, 0.1280, 0.9399],
         [0.9152, 0.6420, 0.0884, 0.3252, 0.5130, 0.0045]]])

In [ ]:
random_tensor2.ndim

3

In [ ]:
# Create random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [4]:
torch.rand(size=(3, 3))

tensor([[0.1705, 0.4990, 0.1473],
        [0.8510, 0.8678, 0.1466],
        [0.0405, 0.5065, 0.3422]])

### Zeros and ones

In [5]:
# Tensors of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [7]:
# Tensors of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [9]:
ones.dtype

torch.float32

### Range of tensors

In [10]:
# Torch.range

In [11]:
torch.range(0, 10)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [12]:
torch.arange(1, 11)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
one = torch.arange(start=1, end=11, step=1)
one

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
thousand = torch.arange(start=0, end=1000, step=77)
thousand

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [16]:
# Tensors like

ten_zeros = torch.zeros_like(input=one)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes among one of the 3 big errors to come across with Pytorch deep learning:
 1. Tensors not in right datatype
 2. Tensors not in right shape
 3. Tensors not on right device

 [Precision in computing](https://en.wikipedia.org/wiki/Precision_(computer_science))

In [23]:
# FLoat 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor (e.g. float32 or float16)
                               device = None, # What device is tensor on ?e.g cpu, cuda
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor
float_32_tensor

tensor([3., 6., 9.])

In [20]:
float_32_tensor.dtype

torch.float32

In [24]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [25]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [26]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [27]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [28]:
int_64_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_64_tensor

tensor([3, 6, 9])

In [29]:
int_64_tensor * int_32_tensor

tensor([ 9, 36, 81])

In [30]:
int_64 = torch.tensor([3, 6, 9], dtype=torch.int64)
int_64

tensor([3, 6, 9])

### Get information  from tensors: How to (tensor attributes)

1. Tensors not in right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not in right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on right device - to get device from a tensor, can use `tensor.device`

In [31]:
# Tensor:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.5311, 0.7108, 0.3810, 0.6937],
        [0.3320, 0.9384, 0.6098, 0.5446],
        [0.8490, 0.0610, 0.5794, 0.6425]])

In [32]:
# Details on some_tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.5311, 0.7108, 0.3810, 0.6937],
        [0.3320, 0.9384, 0.6098, 0.5446],
        [0.8490, 0.0610, 0.5794, 0.6425]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (Tensor Operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [34]:
# Additions
tensoradd = torch.tensor([1, 2, 3]) + 10
tensoradd

tensor([11, 12, 13])

In [35]:
# Subtaction
tensorsubract = torch.tensor([1, 2, 3]) - 10
tensorsubract

tensor([-9, -8, -7])

In [36]:
# Multiplication
tensormultiply = torch.tensor([1, 2, 3]) * 10
tensormultiply

tensor([10, 20, 30])

In [38]:
# Pytroch inbuilt functions
tensormultiply = torch.mul(torch.tensor([1, 2, 3]), 10)
tensormultiply

tensor([10, 20, 30])

from re import M
### MATRIX MULTIPLICATION:

Two main ways  to perform multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

More information on multiplying matrices - [multiplying matrices](https://www.mathsisfun.com/algebra/matrix-multiplying.html)

In [40]:
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [41]:
# Element wise multiplication
print(tensor, "*", tensor) #, "=", tensor * tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [42]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [43]:
# Matrix multiplication by Hand
1*1 + 2*2 + 3*3

14

In [44]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 2.39 ms, sys: 0 ns, total: 2.39 ms
Wall time: 2.07 ms


In [45]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 382 µs, sys: 30 µs, total: 412 µs
Wall time: 316 µs


tensor(14)

In [ ]:
device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')

x = torch.rand(5, 3).to(device)


x = torch.rand(5, 3, device=device)


### Autograd:

Package provide automatic differentiation for all operations on Tensors.
Torch.autograd is an engine for computing the vector-jacobian product. It computes partial derivatives while applying the chain rule.

`Set requires_grad = True:`

In [ ]:
import torch

# requires_grad = True --> tracks all operations on the tensor.
x = torch.randn(3, requires_grad=True)
y = x + 2

# y was created as a result of an operation, so it has a grad_fn attribute.
# grad_fn: references a Function that has created the Tensor
print(x) # created by the user --> grad_fn is None
print(y)
print(y.grad_fn)

tensor([-1.5407, -1.0599,  0.1572], requires_grad=True)
tensor([0.4593, 0.9401, 2.1572], grad_fn=<AddBackward0>)


In [ ]:
# Do more operations on y
z = y * y * 3
print(z)
z = z.mean()
print(z)

tensor([ 0.6329,  2.6513, 13.9610], grad_fn=<MulBackward0>)
tensor(5.7484, grad_fn=<MeanBackward0>)


In [ ]:
z.backward() # dz/dx
print(x.grad)

tensor([0.9186, 1.8802, 4.3145])
