<a href="https://colab.research.google.com/github/EngrIBGIT/Projects_Deep_Learning_PyTorch/blob/main/Project_Deep_Learning_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pytorch Fundamentals

## Resources
`Notebook:` [Pytorch](https://www.learnpytorch.io/00_pytorch_fundamentals/)

`Guided Learning:` [Udacity Deep Learning Pytorch](https://www.udacity.com/course/deep-learning-pytorch--ud188?irclickid=3u50vqRulxyPWoN36uVfJR3zUkFSahxmE2bO040&irgwc=1&utm_source=affiliate&utm_medium=&aff=259799&utm_term=&utm_campaign=_gtc_www_classcentral_com_&utm_content=&adid=788805)

[Deep Learning: CS 182 Spring 2021](https://www.youtube.com/playlist?list=PL_iWQOsE6TfVmKkQHucjPAoRtIJYt8a5A)


In [1]:
!nvidia-smi

Wed Oct  9 14:11:54 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   45C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

import warnings
warnings.filterwarnings('ignore')

In [2]:
print(torch.__version__)

2.4.1+cu121


## Introduction to Tensors: Tensors are the main building blocks of pytorch

#### Creating Tensors; Pytorch tensors are created using `torch.Tensor()` = [Create Tensor](https://pytorch.org/docs/stable/tensors.html)

In [3]:
# Scalar: A way to create tensor in pytorch, has no dimensions its a single number

scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get tensor as python int
scalar.item()

7

In [7]:
# vector; Typically has more than one dimention

vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# MATRIX:
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
MATRIX[1]

tensor([ 9, 10])

In [14]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

__Random Tensors:__

*Why random tensors?*

`Random tensors are important because many neural networks learn by starting with tensor full of numbers and then adjust those random numbers to better represent data`

Start with random numbers --> Look at data --> update random numbers --> --> Look at data --> update random numbers -->

[Torch random tensors](https://pytorch.org/docs/stable/generated/torch.rand.html)

In [18]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4871, 0.1863, 0.5635, 0.8462],
        [0.8449, 0.1131, 0.8301, 0.1739],
        [0.9541, 0.5147, 0.2897, 0.6153]])

In [19]:
random_tensor.ndim

2

In [21]:
random_tensor2 = torch.rand(2, 5, 6)
random_tensor2

tensor([[[0.8799, 0.8630, 0.3519, 0.4966, 0.7470, 0.0569],
         [0.7438, 0.3642, 0.7589, 0.8155, 0.6022, 0.7762],
         [0.5549, 0.1198, 0.8143, 0.1073, 0.6836, 0.3066],
         [0.2271, 0.1944, 0.2165, 0.4513, 0.9756, 0.2348],
         [0.1249, 0.0990, 0.2549, 0.1587, 0.9944, 0.0285]],

        [[0.3677, 0.5970, 0.3848, 0.5676, 0.1055, 0.2327],
         [0.0548, 0.4558, 0.2897, 0.3749, 0.0372, 0.0352],
         [0.9546, 0.0060, 0.2680, 0.9677, 0.6615, 0.0415],
         [0.8682, 0.5734, 0.5947, 0.9019, 0.1280, 0.9399],
         [0.9152, 0.6420, 0.0884, 0.3252, 0.5130, 0.0045]]])

In [22]:
random_tensor2.ndim

3

In [23]:
# Create random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')

x = torch.rand(5, 3).to(device)


x = torch.rand(5, 3, device=device)


### Autograd:

Package provide automatic differentiation for all operations on Tensors.
Torch.autograd is an engine for computing the vector-jacobian product. It computes partial derivatives while applying the chain rule.

`Set requires_grad = True:`

In [ ]:
import torch

# requires_grad = True --> tracks all operations on the tensor.
x = torch.randn(3, requires_grad=True)
y = x + 2

# y was created as a result of an operation, so it has a grad_fn attribute.
# grad_fn: references a Function that has created the Tensor
print(x) # created by the user --> grad_fn is None
print(y)
print(y.grad_fn)

tensor([-1.5407, -1.0599,  0.1572], requires_grad=True)
tensor([0.4593, 0.9401, 2.1572], grad_fn=<AddBackward0>)


In [ ]:
# Do more operations on y
z = y * y * 3
print(z)
z = z.mean()
print(z)

tensor([ 0.6329,  2.6513, 13.9610], grad_fn=<MulBackward0>)
tensor(5.7484, grad_fn=<MeanBackward0>)


In [ ]:
z.backward() # dz/dx
print(x.grad)

tensor([0.9186, 1.8802, 4.3145])
