<a href="https://colab.research.google.com/github/EngrIBGIT/Projects_Deep_Learning_PyTorch/blob/main/Project_Deep_Learning_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pytorch Fundamentals

## Resources
`Notebook:` [Pytorch](https://www.learnpytorch.io/00_pytorch_fundamentals/)

`Guided Learning:` [Udacity Deep Learning Pytorch](https://www.udacity.com/course/deep-learning-pytorch--ud188?irclickid=3u50vqRulxyPWoN36uVfJR3zUkFSahxmE2bO040&irgwc=1&utm_source=affiliate&utm_medium=&aff=259799&utm_term=&utm_campaign=_gtc_www_classcentral_com_&utm_content=&adid=788805)

[Deep Learning: CS 182 Spring 2021](https://www.youtube.com/playlist?list=PL_iWQOsE6TfVmKkQHucjPAoRtIJYt8a5A)


In [1]:
!nvidia-smi

Thu Oct 10 05:28:54 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   44C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

import warnings
warnings.filterwarnings('ignore')

In [3]:
print(torch.__version__)

2.4.1+cu121


## Introduction to Tensors: Tensors are the main building blocks of pytorch

#### Creating Tensors; Pytorch tensors are created using `torch.Tensor()` = [Create Tensor](https://pytorch.org/docs/stable/tensors.html)

In [4]:
# Scalar: A way to create tensor in pytorch, has no dimensions its a single number

scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# Get tensor as python int
scalar.item()

7

In [7]:
# vector; Typically has more than one dimention

vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# MATRIX:
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
MATRIX[1]

tensor([ 9, 10])

In [14]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

__Random Tensors:__

*Why random tensors?*

`Random tensors are important because many neural networks learn by starting with tensor full of numbers and then adjust those random numbers to better represent data`

Start with random numbers --> Look at data --> update random numbers --> Look at data --> update random numbers -->

[Torch random tensors](https://pytorch.org/docs/stable/generated/torch.rand.html)

In [18]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.2920, 0.9899, 0.5187, 0.4389],
        [0.2602, 0.1344, 0.7058, 0.9630],
        [0.0849, 0.4831, 0.7724, 0.6491]])

In [19]:
random_tensor.ndim

2

In [20]:
random_tensor2 = torch.rand(2, 5, 6)
random_tensor2

tensor([[[0.7633, 0.7519, 0.0022, 0.7826, 0.4091, 0.7184],
         [0.3397, 0.8221, 0.9738, 0.5537, 0.0857, 0.7436],
         [0.5177, 0.7016, 0.6991, 0.0893, 0.8657, 0.1333],
         [0.0738, 0.4382, 0.5371, 0.0442, 0.9546, 0.2785],
         [0.2941, 0.4028, 0.3402, 0.3285, 0.5118, 0.9123]],

        [[0.7292, 0.1060, 0.8762, 0.2539, 0.6854, 0.4872],
         [0.3899, 0.3255, 0.6555, 0.4890, 0.3023, 0.1723],
         [0.3741, 0.3497, 0.8628, 0.7280, 0.2664, 0.7257],
         [0.5508, 0.3384, 0.9071, 0.5971, 0.3599, 0.0461],
         [0.1245, 0.7264, 0.3001, 0.3654, 0.7978, 0.1287]]])

In [21]:
random_tensor2.ndim

3

In [22]:
# Create random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [23]:
torch.rand(size=(3, 3))

tensor([[0.3211, 0.7207, 0.3249],
        [0.9665, 0.9062, 0.1771],
        [0.8000, 0.2114, 0.9215]])

### Zeros and ones

In [24]:
# Tensors of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
# Tensors of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [26]:
ones.dtype

torch.float32

### Range of tensors

In [27]:
# Torch.range

In [28]:
torch.range(0, 10)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [29]:
torch.arange(1, 11)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
one = torch.arange(start=1, end=11, step=1)
one

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
thousand = torch.arange(start=0, end=1000, step=77)
thousand

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [32]:
# Tensors like

ten_zeros = torch.zeros_like(input=one)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes among one of the 3 big errors to come across with Pytorch deep learning:
 1. Tensors not in right datatype
 2. Tensors not in right shape
 3. Tensors not on right device

 [Precision in computing](https://en.wikipedia.org/wiki/Precision_(computer_science))

In [33]:
# FLoat 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor (e.g. float32 or float16)
                               device = None, # What device is tensor on ?e.g cpu, cuda
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor
float_32_tensor

tensor([3., 6., 9.])

In [34]:
float_32_tensor.dtype

torch.float32

In [35]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [36]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [37]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [38]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [39]:
int_64_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_64_tensor

tensor([3, 6, 9])

In [40]:
int_64_tensor * int_32_tensor

tensor([ 9, 36, 81])

In [41]:
int_64 = torch.tensor([3, 6, 9], dtype=torch.int64)
int_64

tensor([3, 6, 9])

### Get information  from tensors: How to (tensor attributes)

1. Tensors not in right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not in right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on right device - to get device from a tensor, can use `tensor.device`

In [42]:
# Tensor:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.4358, 0.5996, 0.9305, 0.5024],
        [0.0563, 0.3575, 0.8771, 0.6634],
        [0.3467, 0.8983, 0.3427, 0.1484]])

In [43]:
# Details on some_tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.4358, 0.5996, 0.9305, 0.5024],
        [0.0563, 0.3575, 0.8771, 0.6634],
        [0.3467, 0.8983, 0.3427, 0.1484]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (Tensor Operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [44]:
# Additions
tensoradd = torch.tensor([1, 2, 3]) + 10
tensoradd

tensor([11, 12, 13])

In [45]:
# Subtaction
tensorsubract = torch.tensor([1, 2, 3]) - 10
tensorsubract

tensor([-9, -8, -7])

In [46]:
# Multiplication
tensormultiply = torch.tensor([1, 2, 3]) * 10
tensormultiply

tensor([10, 20, 30])

In [47]:
# Pytroch inbuilt functions
tensormultiply = torch.mul(torch.tensor([1, 2, 3]), 10)
tensormultiply

tensor([10, 20, 30])

from re import M
### MATRIX MULTIPLICATION:

Two main ways  to perform multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

More information on multiplying matrices - [multiplying matrices](https://www.mathsisfun.com/algebra/matrix-multiplying.html)

Two main rules matrix multiplication must satisfy
1. **Inner dimensions** must match:
* `(3,2) @ (3,2)` wont work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work

2. The resulting matrix has shape of **outer dimensions**
* `(2, 3) @ (3, 2)` --> (2, 2)
* `(3, 2) @ (2, 3)` --> (3, 3)


In [48]:
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [49]:
# Element wise multiplication
print(tensor, "*", tensor) #, "=", tensor * tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [50]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [51]:
# Matrix multiplication by Hand
1*1 + 2*2 + 3*3

14

In [52]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 974 µs, sys: 0 ns, total: 974 µs
Wall time: 5.49 ms


In [53]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 83 µs, sys: 819 µs, total: 902 µs
Wall time: 1.9 ms


tensor(14)

In [54]:
# Shapes for Matrix Multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

#torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for writing less code)
torch.matmul(tensor_A, tensor_B

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix shape issues, we can manipulate the shape of one of our tensors using a **transpose**.
A **transpose** switches the axes or dimensions of a given tensor.


In [55]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [56]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [57]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')

x = torch.rand(5, 3).to(device)


x = torch.rand(5, 3, device=device)


### Autograd:

Package provide automatic differentiation for all operations on Tensors.
Torch.autograd is an engine for computing the vector-jacobian product. It computes partial derivatives while applying the chain rule.

`Set requires_grad = True:`

In [ ]:
import torch

# requires_grad = True --> tracks all operations on the tensor.
x = torch.randn(3, requires_grad=True)
y = x + 2

# y was created as a result of an operation, so it has a grad_fn attribute.
# grad_fn: references a Function that has created the Tensor
print(x) # created by the user --> grad_fn is None
print(y)
print(y.grad_fn)

In [ ]:
# Do more operations on y
z = y * y * 3
print(z)
z = z.mean()
print(z)

In [ ]:
z.backward() # dz/dx
print(x.grad)